"""
Execution Entity for the Indian AI Hedge Fund Domain.

Represents an individual order fill execution generated by the broker gateway.
Pure domain entity with zero infrastructure dependencies.
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

from packages.domain.enums.trading import ExecutionStatus, TradeType
from packages.domain.exceptions import ValidationError
from packages.domain.value_objects.core.money import Money
from packages.domain.value_objects.core.price import Price
from packages.domain.value_objects.core.quantity import Quantity
from packages.domain.value_objects.identifiers.ticker import Ticker
from packages.domain.value_objects.identifiers.uuid_wrappers import ExecutionId, OrderId
from packages.domain.value_objects.temporal.timestamps import Timestamp


@dataclass
class Execution:
    """
    Execution Entity owned by BrokerAccount Aggregate Root.

    Attributes:
        id (ExecutionId): Unique execution identifier.
        order_id (OrderId): Parent order ID.
        ticker (Ticker): Executed ticker symbol.
        trade_type (TradeType): Order direction (BUY / SELL).
        quantity (Quantity): Filled share quantity for this fill event.
        price (Price): Filled unit price for this fill event.
        fee (Money): Brokerage commission.
        tax (Money): Transaction taxes (STT, GST, Stamp Duty).
        status (ExecutionStatus): Execution gateway status.
        executed_at (Timestamp): Fill timestamp (UTC).
    """

    order_id: OrderId
    ticker: Ticker
    trade_type: TradeType
    quantity: Quantity
    price: Price
    executed_at: Timestamp
    id: ExecutionId = field(default_factory=ExecutionId.generate)
    fee: Money = field(default_factory=lambda: Money(Decimal("0.00")))
    tax: Money = field(default_factory=lambda: Money(Decimal("0.00")))
    status: ExecutionStatus = ExecutionStatus.EXECUTED

    def __post_init__(self) -> None:
        if not isinstance(self.id, ExecutionId):
            object.__setattr__(self, "id", ExecutionId(self.id))
        if not isinstance(self.order_id, OrderId):
            object.__setattr__(self, "order_id", OrderId(self.order_id))
        if not isinstance(self.trade_type, TradeType):
            object.__setattr__(self, "trade_type", TradeType(self.trade_type))
        if not isinstance(self.status, ExecutionStatus):
            object.__setattr__(self, "status", ExecutionStatus(self.status))
        if not isinstance(self.executed_at, Timestamp):
            object.__setattr__(self, "executed_at", Timestamp(self.executed_at))

        if self.quantity.is_zero():
            raise ValidationError("Execution fill quantity cannot be zero.")

    @property
    def gross_amount(self) -> Money:
        """Return gross fill value (quantity * price)."""
        return self.price.money * self.quantity.value

    @property
    def net_amount(self) -> Money:
        """
        Return net fill cash impact:
        - For BUY: gross + fee + tax (cash debit)
        - For SELL: gross - fee - tax (cash credit)
        """
        frictions = self.fee + self.tax
        if self.trade_type.is_buy():
            return self.gross_amount + frictions
        return self.gross_amount - frictions

    def to_dict(self) -> dict[str, Any]:
        """Serialize Execution to dictionary."""
        return {
            "id": self.id.to_dict(),
            "order_id": self.order_id.to_dict(),
            "ticker": self.ticker.to_dict(),
            "trade_type": self.trade_type.value,
            "quantity": self.quantity.to_dict(),
            "price": self.price.to_dict(),
            "fee": self.fee.to_dict(),
            "tax": self.tax.to_dict(),
            "gross_amount": self.gross_amount.to_dict(),
            "net_amount": self.net_amount.to_dict(),
            "status": self.status.value,
            "executed_at": self.executed_at.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Execution":
        """Deserialize dictionary to Execution entity."""
        return cls(
            id=ExecutionId.from_dict(data["id"]),
            order_id=OrderId.from_dict(data["order_id"]),
            ticker=Ticker.from_dict(data["ticker"]),
            trade_type=TradeType(data["trade_type"]),
            quantity=Quantity.from_dict(data["quantity"]),
            price=Price.from_dict(data["price"]),
            fee=Money.from_dict(data["fee"]) if data.get("fee") else Money(Decimal("0.00")),
            tax=Money.from_dict(data["tax"]) if data.get("tax") else Money(Decimal("0.00")),
            status=ExecutionStatus(data.get("status", "EXECUTED")),
            executed_at=Timestamp.from_dict(data["executed_at"]),
        )

    def __eq__(self, other: Any) -> bool:
        if isinstance(other, Execution):
            return self.id == other.id
        return False

    def __hash__(self) -> int:
        return hash(self.id)
