"""
Strategy & Signal Enums for the Indian AI Hedge Fund Domain.

Defines quant strategy styles, signal classifications, signal strength metrics,
strategy lifecycle statuses, and paper-trading lifecycle statuses.
"""

from enum import StrEnum


class StrategyType(StrEnum):
    """
    Quantitative trading strategy style classifications.
    """

    MOMENTUM = "MOMENTUM"
    SWING = "SWING"
    VALUE = "VALUE"
    QUALITY = "QUALITY"
    GROWTH = "GROWTH"
    SECTOR_ROTATION = "SECTOR_ROTATION"
    ETF = "ETF"
    MULTI_FACTOR = "MULTI_FACTOR"
    STAT_ARB = "STAT_ARB"
    PAIRS = "PAIRS"
    TREND_FOLLOWING = "TREND_FOLLOWING"
    MEAN_REVERSION = "MEAN_REVERSION"

    def is_quantitative_factor(self) -> bool:
        """Return True if the strategy relies primarily on factor analytics."""
        return self in {
            StrategyType.MOMENTUM,
            StrategyType.VALUE,
            StrategyType.QUALITY,
            StrategyType.GROWTH,
            StrategyType.MULTI_FACTOR,
        }

    def is_statistical_arbitrage(self) -> bool:
        """Return True if the strategy uses high-frequency / stat-arb models."""
        return self in {StrategyType.STAT_ARB, StrategyType.PAIRS, StrategyType.MEAN_REVERSION}


class StrategyStatus(StrEnum):
    """
    Lifecycle status of a quantitative trading strategy.
    """

    DRAFT = "DRAFT"
    BACKTESTING = "BACKTESTING"
    PAPER_TRADING = "PAPER_TRADING"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    RETIRED = "RETIRED"

    def is_deployable(self) -> bool:
        """Return True if strategy can be actively deployed in live/paper trading."""
        return self in {StrategyStatus.PAPER_TRADING, StrategyStatus.ACTIVE}


class SignalType(StrEnum):
    """
    Directional trading signals generated by strategies or multi-agent consensus.
    """

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    EXIT_LONG = "EXIT_LONG"
    EXIT_SHORT = "EXIT_SHORT"

    def is_entry(self) -> bool:
        """Return True if this signal initiates a new position."""
        return self in {SignalType.BUY, SignalType.SELL}

    def is_exit(self) -> bool:
        """Return True if this signal closes an existing position."""
        return self in {SignalType.EXIT_LONG, SignalType.EXIT_SHORT}


class SignalStrength(StrEnum):
    """
    Confidence weighting for generated signals.
    """

    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"

    def score_multiplier(self) -> float:
        """Return a numeric multiplier representing signal confidence (0.25 to 1.0)."""
        multipliers = {
            SignalStrength.WEAK: 0.25,
            SignalStrength.MODERATE: 0.50,
            SignalStrength.STRONG: 0.75,
            SignalStrength.VERY_STRONG: 1.00,
        }
        return multipliers[self]


class PaperTradeStatus(StrEnum):
    """
    Lifecycle status of a paper-trading simulation order/position.
    """

    ACTIVE = "ACTIVE"
    EXECUTED = "EXECUTED"
    CLOSED = "CLOSED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

    def is_open(self) -> bool:
        """Return True if the paper trade is actively being tracked."""
        return self in {PaperTradeStatus.ACTIVE, PaperTradeStatus.EXECUTED}

    def is_terminal(self) -> bool:
        """Return True if the paper trade lifecycle has ended."""
        return self in {
            PaperTradeStatus.CLOSED,
            PaperTradeStatus.EXPIRED,
            PaperTradeStatus.CANCELLED,
        }
