"""
Base LLM Adapter Abstraction for Infrastructure Layer.

Extends application LLMPort with provider-agnostic management operations (generate, structured_generate,
health_check, token_count, model_info).
"""

from abc import ABC, abstractmethod
from typing import Any

from packages.application.ports.llm_port import LLMPort


class BaseLLMAdapter(LLMPort, ABC):
    """
    Abstract Base Class for all Infrastructure LLM Adapter implementations.
    """

    @abstractmethod
    def generate(
        self,
        prompt_text: str,
        system_instruction: str | None = None,
        **kwargs: Any,
    ) -> str:
        """
        Generate raw text response from the LLM provider.

        Args:
            prompt_text (str): User prompt text.
            system_instruction (str | None): Optional system prompt instruction.

        Returns:
            str: Raw text generated by model.
        """

    @abstractmethod
    def structured_generate(
        self,
        prompt_text: str,
        response_schema: dict[str, Any],
        system_instruction: str | None = None,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """
        Generate structured JSON output adhering to a response schema.

        Args:
            prompt_text (str): Input prompt text.
            response_schema (dict[str, Any]): Expected JSON schema.
            system_instruction (str | None): Optional system prompt instruction.

        Returns:
            dict[str, Any]: Validated JSON object.
        """

    @abstractmethod
    def health_check(self) -> bool:
        """
        Check if the LLM provider service is healthy and reachable.

        Returns:
            bool: True if service responds successfully.
        """

    @abstractmethod
    def token_count(self, text: str) -> int:
        """
        Calculate token count for an input string.

        Args:
            text (str): Text payload.

        Returns:
            int: Estimated token count.
        """

    @abstractmethod
    def model_info(self) -> dict[str, Any]:
        """
        Retrieve provider and model metadata.

        Returns:
            dict[str, Any]: Provider model specification dictionary.
        """
