"""
Signal & SignalResult Domain Models for the Indian AI Hedge Fund Platform.

Represents quantitative trade signals generated by strategies and their performance evaluation results.
Pure domain models with zero infrastructure dependencies.
"""

import uuid
from dataclasses import dataclass, field
from typing import Any

from packages.domain.enums.strategy import SignalType
from packages.domain.value_objects.core.percentage import Percentage
from packages.domain.value_objects.identifiers.ticker import Ticker
from packages.domain.value_objects.identifiers.uuid_wrappers import StrategyId, TradeId
from packages.domain.value_objects.metrics.scores import ConfidenceScore, RecommendationScore
from packages.domain.value_objects.temporal.timestamps import Timestamp


@dataclass(frozen=True, slots=True)
class Signal:
    """
    Immutable value object representing a quantitative trade signal.

    Attributes:
        id (uuid.UUID): Unique signal identifier.
        strategy_id (StrategyId): Originating strategy ID.
        ticker (Ticker): Target asset ticker symbol.
        signal_type (SignalType): Signal direction (BUY, SELL, HOLD).
        score (ConfidenceScore): Confidence score [0, 1].
        strength (RecommendationScore): Signal strength [-1.0, 1.0].
        generated_at (Timestamp): Signal generation timestamp (UTC).
        reasoning (str): Textual justification for the signal.
    """

    strategy_id: StrategyId
    ticker: Ticker
    signal_type: SignalType
    score: ConfidenceScore
    strength: RecommendationScore
    generated_at: Timestamp
    id: uuid.UUID = field(default_factory=uuid.uuid4)
    reasoning: str = ""

    def __post_init__(self) -> None:
        if not isinstance(self.strategy_id, StrategyId):
            object.__setattr__(self, "strategy_id", StrategyId(self.strategy_id))
        if not isinstance(self.ticker, Ticker):
            object.__setattr__(self, "ticker", Ticker(self.ticker))
        if not isinstance(self.signal_type, SignalType):
            object.__setattr__(self, "signal_type", SignalType(self.signal_type))
        if not isinstance(self.score, ConfidenceScore):
            object.__setattr__(self, "score", ConfidenceScore(self.score))
        if not isinstance(self.strength, RecommendationScore):
            object.__setattr__(self, "strength", RecommendationScore(self.strength))
        if not isinstance(self.generated_at, Timestamp):
            object.__setattr__(self, "generated_at", Timestamp(self.generated_at))

    def to_dict(self) -> dict[str, Any]:
        """Serialize Signal to dictionary."""
        return {
            "id": str(self.id),
            "strategy_id": self.strategy_id.to_dict(),
            "ticker": self.ticker.to_dict(),
            "signal_type": self.signal_type.value,
            "score": self.score.to_dict(),
            "strength": self.strength.to_dict(),
            "generated_at": self.generated_at.to_dict(),
            "reasoning": self.reasoning,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Signal":
        """Deserialize dictionary to Signal."""
        return cls(
            id=uuid.UUID(data["id"]),
            strategy_id=StrategyId.from_dict(data["strategy_id"]),
            ticker=Ticker.from_dict(data["ticker"]),
            signal_type=SignalType(data["signal_type"]),
            score=ConfidenceScore.from_dict(data["score"]),
            strength=RecommendationScore.from_dict(data["strength"]),
            generated_at=Timestamp.from_dict(data["generated_at"]),
            reasoning=data.get("reasoning", ""),
        )


@dataclass(frozen=True, slots=True)
class SignalResult:
    """
    Immutable value object tracking ex-post execution result and return of a Signal.

    Attributes:
        signal (Signal): Originating signal.
        executed_trade_id (Optional[TradeId]): ID of executed trade if filled.
        actual_return_pct (Optional[Percentage]): Realized percentage return of trade signal.
        is_successful (bool): True if signal achieved positive alpha / target return.
    """

    signal: Signal
    executed_trade_id: TradeId | None = None
    actual_return_pct: Percentage | None = None
    is_successful: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialize SignalResult to dictionary."""
        return {
            "signal": self.signal.to_dict(),
            "executed_trade_id": (
                self.executed_trade_id.to_dict() if self.executed_trade_id else None
            ),
            "actual_return_pct": (
                self.actual_return_pct.to_dict() if self.actual_return_pct else None
            ),
            "is_successful": self.is_successful,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SignalResult":
        """Deserialize dictionary to SignalResult."""
        t_id = (
            TradeId.from_dict(data["executed_trade_id"]) if data.get("executed_trade_id") else None
        )
        ret_p = (
            Percentage.from_dict(data["actual_return_pct"])
            if data.get("actual_return_pct")
            else None
        )

        return cls(
            signal=Signal.from_dict(data["signal"]),
            executed_trade_id=t_id,
            actual_return_pct=ret_p,
            is_successful=data.get("is_successful", False),
        )
